Naija_X/urls.py
from django.conf.urls.i18n import urlpatterns
from django.urls import path
from .views import dashboard, profile_list, profile, profile_update
from. import views as user_view
from. import views


app_name = "Naija_X"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path('logout/', user_view.Logout, name ='logout'),
    path('login/', user_view.Login, name ='login'),  
    path('register/', user_view.register, name ='register'),
    path('update_profile/', user_view.profile_update, name ='update_profile'),

] 

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Naija_X.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Naija_X/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_resized import ResizedImageField

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField("self",  related_name="followed_by", symmetrical=False, blank=True)
    image = ResizedImageField(size=[300, 300], quality=75, upload_to="profiles/", blank=True,)

    def __str__(self):
        return self.user.username
    
    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        if created:
            user_profile = Profile(user=instance)
            user_profile.save()
            user_profile.follows.add(instance.profile)
            user_profile.save()


class Posts(models.Model):
    user = models.ForeignKey(
        User, related_name="posts", on_delete=models.CASCADE
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )
    

    

Naija_X/forms.py
from django import forms
from .models import Posts, Profile

class PostForm(forms.ModelForm):
    body = forms.CharField(required=True,  widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Post something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",)

    class Meta:
        model = Posts
        exclude = ("user", )
        





from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length = 20)
    last_name = forms.CharField(max_length = 20)
    email = forms.EmailField()
    phone_no = forms.CharField(max_length = 20)
    error_messages = {'password_mismatch': ("The two password fields didn't match."),}
    password1 = forms.CharField(label=("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=("Password confirmation"), widget=forms.PasswordInput,
        help_text="Enter the same password as above, for verification.")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',  'email', 'phone_no', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

# Create a ProfileUpdateForm to update image.
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

Naija_X/views.py
from django.shortcuts import render, redirect
from .models import Profile, Posts
from .forms import PostForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required



@login_required
def dashboard(request):
    if request.method == "POST":
        form = PostForm(request.POST or None)
        if form.is_valid():
            posts = form.save(commit=False)
            posts.user = request.user
            posts.save()
            return redirect("Naija_X:dashboard")
    
    followed_posts= Posts.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")    
    form = PostForm()
    return render(request, "Naija_X/dashboard.html",{'form':form, 'posts':followed_posts})

def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "Naija_X/profile_list.html", {"profiles": profiles})




def profile(request, pk):
    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
	
    return render(request, "Naija_X/profile.html", {"profile": profile, })

    



#################### index####################################### 
def index(request):
	return render(request, 'Naija_X:dashboard')

########### register here ##################################### 
def register(request):
      
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			email = form.cleaned_data.get('email')
			######################### mail system #################################### 
			htmly = get_template('Naija_X/email.html')
			d = { 'username': username }
			subject, from_email, to = 'welcome to Naija_X', 'your_email@gmail.com', email
			html_content = htmly.render(d)
			msg = EmailMultiAlternatives(subject, html_content, from_email, [to]) # type: ignore
			msg.attach_alternative(html_content, "text/html")
			msg.send()
			################################################################## 
			messages.success(request, f'Your account has been created ! You are now able to log in')
			return redirect('login')
	else:
		form = UserRegisterForm()
	return render(request, 'Naija_X/register.html', {'form': form,'title':'register here'})

################ login forms################################################### 
def Login(request):
	if request.method == 'POST':

		# AuthenticationForm_can_also_be_used__

		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username = username, password = password)
		if user is not None:
			form = login(request, user)
			messages.success(request, f' welcome {username} !!')
			return redirect('Naija_X:dashboard')
		else:
			messages.info(request, f'account does not exist, please sign in')
	form = AuthenticationForm()
	return render(request, 'registration/login.html', {'form':form, 'title':'log in'})

def Logout(request):
	logout(request)
	return redirect('Naija_X:login')
	


@login_required
def profile_update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('Naija_X:profile') # Redirect back to profile page

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'Naija_X/profile.html', context)

Naija_X/templates/Naija_X/dashboard.html
{% extends 'base.html' %}
{% block content %}

<div class="column">    
    {% for post in posts %}
    <div class="box">
        {{post.body}}
        <span class="is-small has-text-grey-light">
            ({{ post.created_at }} by {{ post.user.username }})
        </span>
    </div>
{% endfor %}
</div>
<div class="column is-one-third">
    <div class="block">
        <a href="{% url 'Naija_X:profile_list' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'Naija_X:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
    <div class="block">
        <div class="block">
            <h2 class="title is-2">Add a Post</p>
        </div>
        <div class="block">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
                type="submit">Post
        </button>
    </form>
    </div>
</div>
</div>

{% endblock content %}

Naija_X/templates/Naija_X/email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
		</style>
	</head>
	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank for signing up with Naija_X</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
			</section>
		</div>
	</body>
</html>

Naija_X/templates/Naija_X/profile.html
<!-- dwitter/templates/dwitter/profile.html -->

{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="column">
    <div class="block">
    <h1 class="title is-1">
        {{profile.user.username|upper}}'s Post
    </h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="buttons has-addons">
        {% if profile in user.profile.follows.all %}
            <button class="button is-success is-static">Follow</button>
            <button class="button is-danger" name="follow" value="unfollow">
                Unfollow
            </button>
        {% else %}
            <button class="button is-success" name="follow" value="follow">
                Follow
            </button>
            <button class="button is-danger is-static">Unfollow</button>
        {% endif %}
        </div>
    </form>

    <div class="content">
        {% for post in profile.user.posts.all %}
            <div class="box">
                {{ post.body }}
                <span class="is-small has-text-grey-light">
                    ({{ post.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>
</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'Naija_X:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    
    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">

            <ul style="list-style: none;">
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'Naija_X:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'Naija_X:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <div>
    {% include "Naija_X/update_profile.html" %}
    </div>
</div>


{% endblock content %}

Naija_X/templates/Naija_X/profile_list.html
<!-- dwitter/templates/dwitter/profile_list.html -->

{% extends 'base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
      <div class="card">
        <a href="{% url "Naija_X:profile" profile.id %}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  {% if profile.image %}
                  <img src="{{ profile.image.url }}"
                       alt="Placeholder image">
                       {% endif %}
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">
                  {{ profile.user.first_name }} {{ profile.user.last_name }}
                </p>
                <p class="subtitle is-6">
                  @{{ profile.user.username|lower }}
                </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

{% endfor %}

</div>

{% endblock content %}

Naija_X/templates/Naija_X/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section col-md-8 col-md-offset-2">
<form method="POST" style="border: 1px solid #48c78e;; margin: 4%; padding:10%; border-radius:1%;">
	<div class="form-group">
	{% csrf_token %}
	<fieldset class="form-group">
	{{ form|crispy}}
	</fieldset>
	<center>
	<button style="background: #48c78e;; padding:2%; font-size: 2rem; color:white;" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-check"></span>  sign up</button>
	</center>
	<br />
	<a href="{% url "Naija_X:login" %}" style="text-decoration: none; color: #48c78e;; padding:3%; cursor:pointer;">Already have an account ?</a>
</div>
</form>
</div>
{% endblock %}

Naija_X/templates/Naija_X/update_profile.html
{% load crispy_forms_tags %} 
{% block content %}


  <!-- FORM HERE -->
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Profile Info</legend>
      {{ u_form|crispy }}
      <!-- User form -->
      {{ p_form|crispy }}
      <!-- Profile form -->
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Update</button>
    </div>
  </form>
{% endblock content %}

Naija_X/templates/base.html
<!-- dwitter/templates/base.html -->
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

    <title>Naija_X</title>

    <!-- bootstrap file -->
     
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- bootstrap file-->

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- main css -->
<link rel="stylesheet" type="text/css" href="{% static "index.css" %}" />


<!-- message here -->

{% if messages %}
{% for message in messages %}

<script>
	alert("{{ message }}");
</script>

{% endfor %}
{% endif %}

<!--_______________________________________________-->



</head>

<body class="">
    <header class="row">

        <!-- navbar-->
        <nav class="navbar" role="navigation" aria-label="main navigation" style="background:#48c78e">
            <div class="navbar-brand">
              <a class="navbar-item" href="https://bulma.io">
              </a>
          
              <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
              </a>
            </div>
          
            <div id="navbarBasicExample" class="navbar-menu">
              <div class="navbar-start">
                <a class="navbar-item" href="{% url "Naija_X:dashboard" %}">
                  Home
                </a>
          
                <a class="navbar-item">
                  Documentation
                </a>
          
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link">
                    More
                  </a>
          
                  <div class="navbar-dropdown">
                    <a class="navbar-item ">
                      About
                    </a>
            
                    <a class="navbar-item">
                      Contact
                    </a>
                    
                    <a class="navbar-item">
                      Report an issue
                    </a>
                  </div>
                </div>
              </div>
          
              <div class="navbar-end">
                <div class="navbar-item">
                  <div class="buttons">
                    {% if user.is_authenticated %}
                    <a class="button is-light" href="{% url 'Naija_X:logout' %}">
                        Log Out
                      </a>
                    {% else %}
                    <a class="button is-light" href="{% url "Naija_X:login" %}">
                      Log in
                    </a>
                    <a class="button is-primary" href="{% url "Naija_X:register" %}">
                        <strong>Sign up</strong>
                      </a>
                      {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </nav>

    <div class="container">
        <div class="columns">

            {% block content %}
            {% if user.is_authenticated %}
	        {% include "Naija_X:dashboard" %}
	        {% else %}
	        {% include "Naija_X:login" %}
	        {% endif %}
            {% endblock content %}

        </div>
    </div>
</body>
</html>